#!/bin/sh
#$-S /bin/sh
module load intel/intel-11
module load openmpi/intel-11
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
#$ -cwd
#$ -j y
#$ -N heatq
#$ -q para2.q
#$ -pe orte8x 8#$ -l h_cpu=48:00:00
mpirun a.out

echo 'done'


